---

- hosts: mongo
  remote_user: root
  tasks:
    - name: Add MongoDB apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse

    - name: Install MongoDB
      apt:
        name: mongodb-org
        update_cache: yes

    - name: Start service MongoDB
      service:
        name: mongod
        state: started

    - name: Config MongoDB
      template:
        src: mongod.conf.j2
        dest: /etc/mongod.conf
      notify:
        - restart mongod

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted

- hosts: mongo-cfg
  remote_user: root
  tasks:
    - name: Config MongoDB
      template:
        src: mongod-cfg.conf.j2
        dest: /etc/mongod.conf
      notify:
        - restart mongod

    - name: Initialize mongo rs
      template:
        src: mongo-cfg.js.j2
        dest: /tmp/mongo-cfg.js

    - name: Run mongo rs
      shell: /usr/bin/mongo < /tmp/mongo-cfg.js

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted

- hosts: mongo-shard
  remote_user: root
  tasks:
    - name: Config MongoDB
      template:
        src: mongod-shard.conf.j2
        dest: /etc/mongod.conf
      notify:
        - restart mongod

    - name: Initialize mongo rs
      template:
        src: mongo-shard.js.j2
        dest: /tmp/mongo-shard.js

    - name: Run mongo rs
      shell: /usr/bin/mongo < /tmp/mongo-shard.js

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted

- hosts: mongo-router
  remote_user: root
  tasks:
    - name: Config MongoDB
      template:
        src: mongod-router.conf.j2
        dest: /etc/mongod.conf
      notify:
        - restart mongod

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted
